SELECT
    CANDIDATE.NAME AS CANDIDATES,
    COALESCE(PARTY.NAME, 'Independent') AS PARTY
FROM
    ELECTORATE JOIN CANDIDATE
    ON ELECTORATE.EUID = CANDIDATE.ELECTORATE_EUID
    LEFT OUTER JOIN PARTY ON CANDIDATE.PARTY_CODE = PARTY.CODE
WHERE
    ELECTORATE.NAME = 'Melbourne';