SELECT * FROM RESULTS;

-- Demonstrates John Smith is at the bottom of preferences
SELECT PREFERENCENUMBER, CANDIDATE_CUID, VOTE_VUID, NAME FROM VOTEPREFERENCE INNER JOIN CANDIDATE ON VOTEPREFERENCE.CANDIDATE_CUID = CANDIDATE.CUID ORDER BY PREFERENCENUMBER ASC, CANDIDATE_CUID;

EXECUTE PRIMARYVOTECOUNT('Melbourne');

SELECT ELIMROUNDNO, VOTECOUNT, NAME FROM RESULTS INNER JOIN CANDIDATE ON RESULTS.CANDIDATE_CUID = CANDIDATE.CUID WHERE ELECTORATE_EUID = (SELECT EUID FROM ELECTORATE WHERE NAME = 'Melbourne') ORDER BY ELIMROUNDNO DESC, VOTECOUNT DESC;

-- RESET

DELETE FROM RESULTS;
