SELECT * FROM RESULTS;

EXECUTE DISTRIBUTEPREFERENCES('Melbourne');

SELECT ELIMROUNDNO, VOTECOUNT, NAME FROM RESULTS JOIN CANDIDATE ON RESULTS.CANDIDATE_CUID = CANDIDATE.CUID ORDER BY ELIMROUNDNO DESC, VOTECOUNT DESC;

-- Demonstrate the member elect
SELECT ELECTORATE.NAME as Electorate, CANDIDATE.NAME as MemberElect FROM MEMBERELECT JOIN CANDIDATE ON MEMBERELECT.CANDIDATE_CUID = CANDIDATE.CUID JOIN ELECTORATE ON MEMBERELECT.ELECTORATE_EUID = ELECTORATE.EUID;

-- RESETS

DELETE FROM RESULTS;

DELETE FROM ELIMINATION;

DELETE FROM MEMBERELECT;

SELECT * FROM VOTEPREFERENCE;